"""forignkey

Revision ID: 8bfaa26d17d1
Revises: 26d8aa958566
Create Date: 2025-05-22 19:19:24.127609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bfaa26d17d1'
down_revision: Union[str, None] = '26d8aa958566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('professor_id', sa.Integer(), nullable=True))
    op.add_column('course', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course', 'professor', ['professor_id'], ['id'])
    op.create_foreign_key(None, 'course', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_column('course', 'category_id')
    op.drop_column('course', 'professor_id')
    # ### end Alembic commands ###
